name: Generate Terraform Docs
#on:
#  push:
#    branches: [ "master" ]

on:
  workflow_call:

permissions:
  repository-projects: write
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write

jobs:
  reusable-docs-wf:
    runs-on: ubuntu-latest  # Run the workflow on an Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Install Terraform Docs
        uses: terraform-docs/gh-actions@main  # Action to generate Terraform documentation
        with:
          working_dir: .  # Use the current directory (adjust if needed)
          output-file: README.md  # Update the README file with generated docs
          output-method: inject  # Inject the documentation into the README
          git-push: "true"
